name: PHP Lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Find PHP files
        id: files
        shell: bash
        run: |
          set -e
          mapfile -t files < <(git ls-files '*.php')
          echo "Gefundene Dateien: ${#files[@]}"
          printf 'files<<EOF\n' >> $GITHUB_OUTPUT
          for f in "${files[@]}"; do echo "$f"; done >> $GITHUB_OUTPUT
          printf 'EOF\n' >> $GITHUB_OUTPUT

      - name: Syntax-Check (php -l)
        if: steps.files.outputs.files != ''
        shell: bash
        run: |
          failed=0
          while IFS= read -r file; do
            echo "Prüfe $file"
            if ! php -l "$file" > /dev/null; then
              echo "Fehler in: $file"
              failed=1
            fi
          done <<< "${{ steps.files.outputs.files }}"
          exit $failed

      - name: Hinweis bei keinen PHP-Dateien
        if: steps.files.outputs.files == ''
        run: echo "Keine PHP-Dateien gefunden – überspringe Lint."
